iconCss: //at.alicdn.com/t/font_2170709_houtddm7q6g.css

avatar: ./IMG_0049.jpeg

menus:
  - icon: iconfont icon-bxs-home
    name: 首页
  - icon: iconfont icon-bx-collection
    name: 收集

tabs:
  - label: 最新
    value: newest
  - label: 搜索
    value: search
  - label: 类别
    value: category
  - label: 归档
    value: achieve
