iconCss: //at.alicdn.com/t/font_2170709_43uj0ismij6.css

avatar: ./IMG_0049.jpeg

menus:
  - icon: iconfont icon-bxs-home
    key: articles
    name: 全部文章
  - icon: iconfont icon-bxs-bookmarks
    name: 文章标签
    key: tags
  - icon: iconfont icon-bxs-bot
    name: 关于
    key: about

tabs:
  - label: 最新
    value: newest
  - label: 搜索
    value: search
  - label: 类别
    value: category
  - label: 归档
    value: achieve

defaultSrc: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1604306099773&di=4e6f5d4ef87d3aefbda0262aea04b252&imgtype=0&src=http%3A%2F%2Fattach.bbs.miui.com%2Fforum%2F201303%2F18%2F233119quyrec7to3ws3rco.jpg
