iconCss: //at.alicdn.com/t/font_2170709_lofk1of7ffq.css

avatar: ./IMG_0049.jpeg

menus:
  - icon: iconfont icon-bxs-home
    name: 首页
  - icon: iconfont icon-bx-collection
    name: 收集

tabs:
  - label: 最新
    value: newest
  - label: 搜索
    value: search
  - label: 类别
    value: category
  - label: 类别
    value: category
  - label: 类别
    value: category
  - label: 类别
    value: category

defaultSrc: https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=1714871622,3719228887&fm=26&gp=0.jpg